// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package dns

import (
	"github.com/pkg/errors"
	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

// Manages a V2 recordset resource within Enterprise Cloud.
type RecordSet struct {
	s *pulumi.ResourceState
}

// NewRecordSet registers a new resource with the given unique name, arguments, and options.
func NewRecordSet(ctx *pulumi.Context,
	name string, args *RecordSetArgs, opts ...pulumi.ResourceOpt) (*RecordSet, error) {
	if args == nil || args.Record == nil {
		return nil, errors.New("missing required argument 'Record'")
	}
	if args == nil || args.Ttl == nil {
		return nil, errors.New("missing required argument 'Ttl'")
	}
	if args == nil || args.Type == nil {
		return nil, errors.New("missing required argument 'Type'")
	}
	if args == nil || args.ZoneId == nil {
		return nil, errors.New("missing required argument 'ZoneId'")
	}
	inputs := make(map[string]interface{})
	if args == nil {
		inputs["description"] = nil
		inputs["name"] = nil
		inputs["record"] = nil
		inputs["ttl"] = nil
		inputs["type"] = nil
		inputs["zoneId"] = nil
	} else {
		inputs["description"] = args.Description
		inputs["name"] = args.Name
		inputs["record"] = args.Record
		inputs["ttl"] = args.Ttl
		inputs["type"] = args.Type
		inputs["zoneId"] = args.ZoneId
	}
	s, err := ctx.RegisterResource("ecl:dns/recordSet:RecordSet", name, true, inputs, opts...)
	if err != nil {
		return nil, err
	}
	return &RecordSet{s: s}, nil
}

// GetRecordSet gets an existing RecordSet resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetRecordSet(ctx *pulumi.Context,
	name string, id pulumi.ID, state *RecordSetState, opts ...pulumi.ResourceOpt) (*RecordSet, error) {
	inputs := make(map[string]interface{})
	if state != nil {
		inputs["description"] = state.Description
		inputs["name"] = state.Name
		inputs["record"] = state.Record
		inputs["ttl"] = state.Ttl
		inputs["type"] = state.Type
		inputs["zoneId"] = state.ZoneId
	}
	s, err := ctx.ReadResource("ecl:dns/recordSet:RecordSet", name, id, inputs, opts...)
	if err != nil {
		return nil, err
	}
	return &RecordSet{s: s}, nil
}

// URN is this resource's unique name assigned by Pulumi.
func (r *RecordSet) URN() *pulumi.URNOutput {
	return r.s.URN
}

// ID is this resource's unique identifier assigned by its provider.
func (r *RecordSet) ID() *pulumi.IDOutput {
	return r.s.ID
}

// Description for the recordset.
func (r *RecordSet) Description() *pulumi.StringOutput {
	return (*pulumi.StringOutput)(r.s.State["description"])
}

// DNS Name for the recordset.
func (r *RecordSet) Name() *pulumi.StringOutput {
	return (*pulumi.StringOutput)(r.s.State["name"])
}

// Data for the recordset.
func (r *RecordSet) Record() *pulumi.StringOutput {
	return (*pulumi.StringOutput)(r.s.State["record"])
}

// TTL (Time to Live) for the recordset.
func (r *RecordSet) Ttl() *pulumi.IntOutput {
	return (*pulumi.IntOutput)(r.s.State["ttl"])
}

// RRTYPE of the recordset. 
// Valid Values: A | AAAA | MX | CNAME | SRV | SPF | TXT | PTR | NS
func (r *RecordSet) Type() *pulumi.StringOutput {
	return (*pulumi.StringOutput)(r.s.State["type"])
}

// Zone ID for the recordset.
func (r *RecordSet) ZoneId() *pulumi.StringOutput {
	return (*pulumi.StringOutput)(r.s.State["zoneId"])
}

// Input properties used for looking up and filtering RecordSet resources.
type RecordSetState struct {
	// Description for the recordset.
	Description interface{}
	// DNS Name for the recordset.
	Name interface{}
	// Data for the recordset.
	Record interface{}
	// TTL (Time to Live) for the recordset.
	Ttl interface{}
	// RRTYPE of the recordset. 
	// Valid Values: A | AAAA | MX | CNAME | SRV | SPF | TXT | PTR | NS
	Type interface{}
	// Zone ID for the recordset.
	ZoneId interface{}
}

// The set of arguments for constructing a RecordSet resource.
type RecordSetArgs struct {
	// Description for the recordset.
	Description interface{}
	// DNS Name for the recordset.
	Name interface{}
	// Data for the recordset.
	Record interface{}
	// TTL (Time to Live) for the recordset.
	Ttl interface{}
	// RRTYPE of the recordset. 
	// Valid Values: A | AAAA | MX | CNAME | SRV | SPF | TXT | PTR | NS
	Type interface{}
	// Zone ID for the recordset.
	ZoneId interface{}
}
