// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

export function getTenant(args: GetTenantArgs, opts?: pulumi.InvokeOptions): Promise<GetTenantResult> {
    return pulumi.runtime.invoke("ecl:sss/getTenant:getTenant", {
        "contractId": args.contractId,
        "description": args.description,
        "region": args.region,
        "startTime": args.startTime,
        "tenantId": args.tenantId,
        "tenantName": args.tenantName,
    }, opts);
}

/**
 * A collection of arguments for invoking getTenant.
 */
export interface GetTenantArgs {
    readonly contractId?: string;
    readonly description?: string;
    readonly region?: string;
    readonly startTime?: string;
    readonly tenantId?: string;
    readonly tenantName: string;
}

/**
 * A collection of values returned by getTenant.
 */
export interface GetTenantResult {
    /**
     * id is the provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
}
