// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package sss

import (
	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

func LookupTenant(ctx *pulumi.Context, args *GetTenantArgs) (*GetTenantResult, error) {
	inputs := make(map[string]interface{})
	if args != nil {
		inputs["contractId"] = args.ContractId
		inputs["description"] = args.Description
		inputs["region"] = args.Region
		inputs["startTime"] = args.StartTime
		inputs["tenantId"] = args.TenantId
		inputs["tenantName"] = args.TenantName
	}
	outputs, err := ctx.Invoke("ecl:sss/getTenant:getTenant", inputs)
	if err != nil {
		return nil, err
	}
	return &GetTenantResult{
		Id: outputs["id"],
	}, nil
}

// A collection of arguments for invoking getTenant.
type GetTenantArgs struct {
	ContractId interface{}
	Description interface{}
	Region interface{}
	StartTime interface{}
	TenantId interface{}
	TenantName interface{}
}

// A collection of values returned by getTenant.
type GetTenantResult struct {
	// id is the provider-assigned unique ID for this managed resource.
	Id interface{}
}
