// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package storage

import (
	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

func LookupVolumeType(ctx *pulumi.Context, args *GetVolumeTypeArgs) (*GetVolumeTypeResult, error) {
	inputs := make(map[string]interface{})
	if args != nil {
		inputs["extraSpecs"] = args.ExtraSpecs
		inputs["name"] = args.Name
		inputs["volumeTypeId"] = args.VolumeTypeId
	}
	outputs, err := ctx.Invoke("ecl:storage/getVolumeType:getVolumeType", inputs)
	if err != nil {
		return nil, err
	}
	return &GetVolumeTypeResult{
		ExtraSpecs: outputs["extraSpecs"],
		Id: outputs["id"],
	}, nil
}

// A collection of arguments for invoking getVolumeType.
type GetVolumeTypeArgs struct {
	ExtraSpecs interface{}
	Name interface{}
	VolumeTypeId interface{}
}

// A collection of values returned by getVolumeType.
type GetVolumeTypeResult struct {
	ExtraSpecs interface{}
	// id is the provider-assigned unique ID for this managed resource.
	Id interface{}
}
