// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package storage

import (
	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

func LookupVirtualStorage(ctx *pulumi.Context, args *GetVirtualStorageArgs) (*GetVirtualStorageResult, error) {
	inputs := make(map[string]interface{})
	if args != nil {
		inputs["description"] = args.Description
		inputs["hostRoutes"] = args.HostRoutes
		inputs["ipAddrPool"] = args.IpAddrPool
		inputs["name"] = args.Name
		inputs["networkId"] = args.NetworkId
		inputs["subnetId"] = args.SubnetId
		inputs["virtualStorageId"] = args.VirtualStorageId
		inputs["volumeTypeId"] = args.VolumeTypeId
	}
	outputs, err := ctx.Invoke("ecl:storage/getVirtualStorage:getVirtualStorage", inputs)
	if err != nil {
		return nil, err
	}
	return &GetVirtualStorageResult{
		Id: outputs["id"],
	}, nil
}

// A collection of arguments for invoking getVirtualStorage.
type GetVirtualStorageArgs struct {
	Description interface{}
	HostRoutes interface{}
	IpAddrPool interface{}
	Name interface{}
	NetworkId interface{}
	SubnetId interface{}
	VirtualStorageId interface{}
	VolumeTypeId interface{}
}

// A collection of values returned by getVirtualStorage.
type GetVirtualStorageResult struct {
	// id is the provider-assigned unique ID for this managed resource.
	Id interface{}
}
