// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package storage

import (
	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

func LookupVolume(ctx *pulumi.Context, args *GetVolumeArgs) (*GetVolumeResult, error) {
	inputs := make(map[string]interface{})
	if args != nil {
		inputs["availabilityZone"] = args.AvailabilityZone
		inputs["description"] = args.Description
		inputs["initiatorIqns"] = args.InitiatorIqns
		inputs["iopsPerGb"] = args.IopsPerGb
		inputs["name"] = args.Name
		inputs["size"] = args.Size
		inputs["throughput"] = args.Throughput
		inputs["virtualStorageId"] = args.VirtualStorageId
		inputs["volumeId"] = args.VolumeId
	}
	outputs, err := ctx.Invoke("ecl:storage/getVolume:getVolume", inputs)
	if err != nil {
		return nil, err
	}
	return &GetVolumeResult{
		AvailabilityZone: outputs["availabilityZone"],
		Id: outputs["id"],
	}, nil
}

// A collection of arguments for invoking getVolume.
type GetVolumeArgs struct {
	AvailabilityZone interface{}
	Description interface{}
	InitiatorIqns interface{}
	IopsPerGb interface{}
	Name interface{}
	Size interface{}
	Throughput interface{}
	VirtualStorageId interface{}
	VolumeId interface{}
}

// A collection of values returned by getVolume.
type GetVolumeResult struct {
	AvailabilityZone interface{}
	// id is the provider-assigned unique ID for this managed resource.
	Id interface{}
}
