// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

export function getFlavor(args?: GetFlavorArgs, opts?: pulumi.InvokeOptions): Promise<GetFlavorResult> {
    args = args || {};
    return pulumi.runtime.invoke("ecl:compute/getFlavor:getFlavor", {
        "disk": args.disk,
        "minDisk": args.minDisk,
        "minRam": args.minRam,
        "name": args.name,
        "ram": args.ram,
        "region": args.region,
        "rxTxFactor": args.rxTxFactor,
        "swap": args.swap,
        "vcpus": args.vcpus,
    }, opts);
}

/**
 * A collection of arguments for invoking getFlavor.
 */
export interface GetFlavorArgs {
    readonly disk?: number;
    readonly minDisk?: number;
    readonly minRam?: number;
    readonly name?: string;
    readonly ram?: number;
    readonly region?: string;
    readonly rxTxFactor?: number;
    readonly swap?: number;
    readonly vcpus?: number;
}

/**
 * A collection of values returned by getFlavor.
 */
export interface GetFlavorResult {
    readonly disk: number;
    readonly isPublic: boolean;
    readonly minDisk: number;
    readonly minRam: number;
    readonly name: string;
    readonly ram: number;
    readonly region: string;
    readonly rxTxFactor: number;
    readonly swap: number;
    readonly vcpus: number;
    /**
     * id is the provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
}
