// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

export function getVolume(args?: GetVolumeArgs, opts?: pulumi.InvokeOptions): Promise<GetVolumeResult> {
    args = args || {};
    return pulumi.runtime.invoke("ecl:storage/getVolume:getVolume", {
        "availabilityZone": args.availabilityZone,
        "description": args.description,
        "initiatorIqns": args.initiatorIqns,
        "iopsPerGb": args.iopsPerGb,
        "name": args.name,
        "size": args.size,
        "throughput": args.throughput,
        "virtualStorageId": args.virtualStorageId,
        "volumeId": args.volumeId,
    }, opts);
}

/**
 * A collection of arguments for invoking getVolume.
 */
export interface GetVolumeArgs {
    readonly availabilityZone?: string;
    readonly description?: string;
    readonly initiatorIqns?: string[];
    readonly iopsPerGb?: string;
    readonly name?: string;
    readonly size?: number;
    readonly throughput?: string;
    readonly virtualStorageId?: string;
    readonly volumeId?: string;
}

/**
 * A collection of values returned by getVolume.
 */
export interface GetVolumeResult {
    readonly availabilityZone: string;
    /**
     * id is the provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
}
