// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package imagestorages

import (
	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

func LookupImage(ctx *pulumi.Context, args *GetImageArgs) (*GetImageResult, error) {
	inputs := make(map[string]interface{})
	if args != nil {
		inputs["memberStatus"] = args.MemberStatus
		inputs["mostRecent"] = args.MostRecent
		inputs["name"] = args.Name
		inputs["owner"] = args.Owner
		inputs["properties"] = args.Properties
		inputs["region"] = args.Region
		inputs["sizeMax"] = args.SizeMax
		inputs["sizeMin"] = args.SizeMin
		inputs["sortDirection"] = args.SortDirection
		inputs["sortKey"] = args.SortKey
		inputs["tag"] = args.Tag
		inputs["visibility"] = args.Visibility
	}
	outputs, err := ctx.Invoke("ecl:imagestorages/getImage:getImage", inputs)
	if err != nil {
		return nil, err
	}
	return &GetImageResult{
		Checksum: outputs["checksum"],
		ContainerFormat: outputs["containerFormat"],
		CreatedAt: outputs["createdAt"],
		DiskFormat: outputs["diskFormat"],
		File: outputs["file"],
		MemberStatus: outputs["memberStatus"],
		Metadata: outputs["metadata"],
		MinDiskGb: outputs["minDiskGb"],
		MinRamMb: outputs["minRamMb"],
		Name: outputs["name"],
		Owner: outputs["owner"],
		Properties: outputs["properties"],
		Protected: outputs["protected"],
		Region: outputs["region"],
		Schema: outputs["schema"],
		SizeBytes: outputs["sizeBytes"],
		Tag: outputs["tag"],
		UpdatedAt: outputs["updatedAt"],
		Visibility: outputs["visibility"],
		Id: outputs["id"],
	}, nil
}

// A collection of arguments for invoking getImage.
type GetImageArgs struct {
	MemberStatus interface{}
	MostRecent interface{}
	Name interface{}
	Owner interface{}
	Properties interface{}
	Region interface{}
	SizeMax interface{}
	SizeMin interface{}
	SortDirection interface{}
	SortKey interface{}
	Tag interface{}
	Visibility interface{}
}

// A collection of values returned by getImage.
type GetImageResult struct {
	Checksum interface{}
	ContainerFormat interface{}
	CreatedAt interface{}
	DiskFormat interface{}
	File interface{}
	MemberStatus interface{}
	Metadata interface{}
	MinDiskGb interface{}
	MinRamMb interface{}
	Name interface{}
	Owner interface{}
	Properties interface{}
	Protected interface{}
	Region interface{}
	Schema interface{}
	SizeBytes interface{}
	Tag interface{}
	UpdatedAt interface{}
	Visibility interface{}
	// id is the provider-assigned unique ID for this managed resource.
	Id interface{}
}
