# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import json
import warnings
import pulumi
import pulumi.runtime
from .. import utilities, tables

class Volume(pulumi.CustomResource):
    attachments: pulumi.Output[list]
    availability_zone: pulumi.Output[str]
    description: pulumi.Output[str]
    image_id: pulumi.Output[str]
    metadata: pulumi.Output[dict]
    name: pulumi.Output[str]
    region: pulumi.Output[str]
    size: pulumi.Output[int]
    source_replica: pulumi.Output[str]
    volume_type: pulumi.Output[str]
    def __init__(__self__, resource_name, opts=None, availability_zone=None, description=None, image_id=None, metadata=None, name=None, region=None, size=None, source_replica=None, volume_type=None, __name__=None, __opts__=None):
        """
        Create a Volume resource with the given unique name, props, and options.
        
        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[str] availability_zone
        :param pulumi.Input[str] description
        :param pulumi.Input[str] image_id
        :param pulumi.Input[dict] metadata
        :param pulumi.Input[str] name
        :param pulumi.Input[str] region
        :param pulumi.Input[int] size
        :param pulumi.Input[str] source_replica
        :param pulumi.Input[str] volume_type
        """
        if __name__ is not None:
            warnings.warn("explicit use of __name__ is deprecated", DeprecationWarning)
            resource_name = __name__
        if __opts__ is not None:
            warnings.warn("explicit use of __opts__ is deprecated, use 'opts' instead", DeprecationWarning)
            opts = __opts__
        if not resource_name:
            raise TypeError('Missing resource name argument (for URN creation)')
        if not isinstance(resource_name, str):
            raise TypeError('Expected resource name to be a string')
        if opts and not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')

        __props__ = dict()

        __props__['availability_zone'] = availability_zone

        __props__['description'] = description

        __props__['image_id'] = image_id

        __props__['metadata'] = metadata

        __props__['name'] = name

        __props__['region'] = region

        if size is None:
            raise TypeError('Missing required property size')
        __props__['size'] = size

        __props__['source_replica'] = source_replica

        __props__['volume_type'] = volume_type

        __props__['attachments'] = None

        super(Volume, __self__).__init__(
            'ecl:compute/volume:Volume',
            resource_name,
            __props__,
            opts)


    def translate_output_property(self, prop):
        return tables._CAMEL_TO_SNAKE_CASE_TABLE.get(prop) or prop

    def translate_input_property(self, prop):
        return tables._SNAKE_TO_CAMEL_CASE_TABLE.get(prop) or prop

