# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import pulumi
import pulumi.runtime
from .. import utilities

class VolumeAttach(pulumi.CustomResource):
    def __init__(__self__, __name__, __opts__=None, device=None, region=None, server_id=None, volume_id=None):
        """Create a VolumeAttach resource with the given unique name, props, and options."""
        if not __name__:
            raise TypeError('Missing resource name argument (for URN creation)')
        if not isinstance(__name__, basestring):
            raise TypeError('Expected resource name to be a string')
        if __opts__ and not isinstance(__opts__, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')

        __props__ = dict()

        if device and not isinstance(device, basestring):
            raise TypeError('Expected property device to be a basestring')
        __self__.device = device
        __props__['device'] = device

        if region and not isinstance(region, basestring):
            raise TypeError('Expected property region to be a basestring')
        __self__.region = region
        __props__['region'] = region

        if not server_id:
            raise TypeError('Missing required property server_id')
        elif not isinstance(server_id, basestring):
            raise TypeError('Expected property server_id to be a basestring')
        __self__.server_id = server_id
        __props__['serverId'] = server_id

        if not volume_id:
            raise TypeError('Missing required property volume_id')
        elif not isinstance(volume_id, basestring):
            raise TypeError('Expected property volume_id to be a basestring')
        __self__.volume_id = volume_id
        __props__['volumeId'] = volume_id

        super(VolumeAttach, __self__).__init__(
            'ecl:compute/volumeAttach:VolumeAttach',
            __name__,
            __props__,
            __opts__)

    def set_outputs(self, outs):
        if 'device' in outs:
            self.device = outs['device']
        if 'region' in outs:
            self.region = outs['region']
        if 'serverId' in outs:
            self.server_id = outs['serverId']
        if 'volumeId' in outs:
            self.volume_id = outs['volumeId']
