# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import pulumi
import pulumi.runtime
from .. import utilities

class GetTenantResult(object):
    """
    A collection of values returned by getTenant.
    """
    def __init__(__self__, id=None):
        if id and not isinstance(id, basestring):
            raise TypeError('Expected argument id to be a basestring')
        __self__.id = id
        """
        id is the provider-assigned unique ID for this managed resource.
        """

def get_tenant(contract_id=None, description=None, region=None, start_time=None, tenant_id=None, tenant_name=None):
    __args__ = dict()

    __args__['contractId'] = contract_id
    __args__['description'] = description
    __args__['region'] = region
    __args__['startTime'] = start_time
    __args__['tenantId'] = tenant_id
    __args__['tenantName'] = tenant_name
    __ret__ = pulumi.runtime.invoke('ecl:sss/getTenant:getTenant', __args__)

    return GetTenantResult(
        id=__ret__.get('id'))
