// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

export function getDnsZone(args?: GetDnsZoneArgs, opts?: pulumi.InvokeOptions): Promise<GetDnsZoneResult> {
    args = args || {};
    return pulumi.runtime.invoke("ecl:dns/getDnsZone:getDnsZone", {
        "attributes": args.attributes,
        "createdAt": args.createdAt,
        "description": args.description,
        "domainName": args.domainName,
        "email": args.email,
        "masters": args.masters,
        "name": args.name,
        "poolId": args.poolId,
        "projectId": args.projectId,
        "region": args.region,
        "serial": args.serial,
        "status": args.status,
        "transferredAt": args.transferredAt,
        "ttl": args.ttl,
        "type": args.type,
        "updatedAt": args.updatedAt,
        "version": args.version,
    }, opts);
}

/**
 * A collection of arguments for invoking getDnsZone.
 */
export interface GetDnsZoneArgs {
    readonly attributes?: {[key: string]: any};
    readonly createdAt?: string;
    readonly description?: string;
    readonly domainName?: string;
    readonly email?: string;
    readonly masters?: string[];
    readonly name?: string;
    readonly poolId?: string;
    readonly projectId?: string;
    readonly region?: string;
    readonly serial?: number;
    readonly status?: string;
    readonly transferredAt?: string;
    readonly ttl?: number;
    readonly type?: string;
    readonly updatedAt?: string;
    readonly version?: number;
}

/**
 * A collection of values returned by getDnsZone.
 */
export interface GetDnsZoneResult {
    readonly attributes: {[key: string]: any};
    readonly createdAt: string;
    readonly description: string;
    readonly domainName: string;
    readonly email: string;
    readonly masters: string[];
    readonly name: string;
    readonly poolId: string;
    readonly projectId: string;
    readonly region: string;
    readonly serial: number;
    readonly status: string;
    readonly transferredAt: string;
    readonly ttl: number;
    readonly type: string;
    readonly updatedAt: string;
    readonly version: number;
    /**
     * id is the provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
}
