// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package network

import (
	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

// Use this data source to get the ID and Details of an Enterprise Cloud Internet gateway.
func LookupInternetGateway(ctx *pulumi.Context, args *GetInternetGatewayArgs) (*GetInternetGatewayResult, error) {
	inputs := make(map[string]interface{})
	if args != nil {
		inputs["description"] = args.Description
		inputs["internetGatewayId"] = args.InternetGatewayId
		inputs["internetServiceId"] = args.InternetServiceId
		inputs["name"] = args.Name
		inputs["qosOptionId"] = args.QosOptionId
		inputs["region"] = args.Region
		inputs["status"] = args.Status
		inputs["tenantId"] = args.TenantId
	}
	outputs, err := ctx.Invoke("ecl:network/getInternetGateway:getInternetGateway", inputs)
	if err != nil {
		return nil, err
	}
	return &GetInternetGatewayResult{
		Description: outputs["description"],
		InternetGatewayId: outputs["internetGatewayId"],
		InternetServiceId: outputs["internetServiceId"],
		Name: outputs["name"],
		QosOptionId: outputs["qosOptionId"],
		Region: outputs["region"],
		Status: outputs["status"],
		TenantId: outputs["tenantId"],
		Id: outputs["id"],
	}, nil
}

// A collection of arguments for invoking getInternetGateway.
type GetInternetGatewayArgs struct {
	// Description of the Internet Gateway resource.
	Description interface{}
	// Unique ID of the Internet Gateway resource.
	InternetGatewayId interface{}
	// Internet Service instantiated by this Gateway.
	InternetServiceId interface{}
	// Name of the Internet Gateway resource.
	Name interface{}
	// Quality of Service options selected for this Gateway.
	QosOptionId interface{}
	// The region in which to obtain the V2 Network client.
	// If omitted, the `region` argument of the provider is used.
	Region interface{}
	// The Internet Gateway status.
	Status interface{}
	// Tenant ID of the owner (UUID).
	TenantId interface{}
}

// A collection of values returned by getInternetGateway.
type GetInternetGatewayResult struct {
	// See Argument Reference above.
	Description interface{}
	InternetGatewayId interface{}
	// See Argument Reference above.
	InternetServiceId interface{}
	// See Argument Reference above.
	Name interface{}
	// See Argument Reference above.
	QosOptionId interface{}
	// See Argument Reference above.
	Region interface{}
	// See Argument Reference above.
	Status interface{}
	// See Argument Reference above.
	TenantId interface{}
	// id is the provider-assigned unique ID for this managed resource.
	Id interface{}
}
