// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package network

import (
	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

func LookupStaticRoute(ctx *pulumi.Context, args *GetStaticRouteArgs) (*GetStaticRouteResult, error) {
	inputs := make(map[string]interface{})
	if args != nil {
		inputs["awsGwId"] = args.AwsGwId
		inputs["azureGwId"] = args.AzureGwId
		inputs["description"] = args.Description
		inputs["destination"] = args.Destination
		inputs["gcpGwId"] = args.GcpGwId
		inputs["interdcGwId"] = args.InterdcGwId
		inputs["internetGwId"] = args.InternetGwId
		inputs["name"] = args.Name
		inputs["nexthop"] = args.Nexthop
		inputs["region"] = args.Region
		inputs["serviceType"] = args.ServiceType
		inputs["staticRouteId"] = args.StaticRouteId
		inputs["status"] = args.Status
		inputs["tenantId"] = args.TenantId
		inputs["vpnGwId"] = args.VpnGwId
	}
	outputs, err := ctx.Invoke("ecl:network/getStaticRoute:getStaticRoute", inputs)
	if err != nil {
		return nil, err
	}
	return &GetStaticRouteResult{
		AwsGwId: outputs["awsGwId"],
		AzureGwId: outputs["azureGwId"],
		Description: outputs["description"],
		Destination: outputs["destination"],
		GcpGwId: outputs["gcpGwId"],
		InterdcGwId: outputs["interdcGwId"],
		InternetGwId: outputs["internetGwId"],
		Name: outputs["name"],
		Nexthop: outputs["nexthop"],
		Region: outputs["region"],
		ServiceType: outputs["serviceType"],
		StaticRouteId: outputs["staticRouteId"],
		TenantId: outputs["tenantId"],
		VpnGwId: outputs["vpnGwId"],
		Id: outputs["id"],
	}, nil
}

// A collection of arguments for invoking getStaticRoute.
type GetStaticRouteArgs struct {
	AwsGwId interface{}
	AzureGwId interface{}
	Description interface{}
	Destination interface{}
	GcpGwId interface{}
	InterdcGwId interface{}
	InternetGwId interface{}
	Name interface{}
	Nexthop interface{}
	Region interface{}
	ServiceType interface{}
	StaticRouteId interface{}
	Status interface{}
	TenantId interface{}
	VpnGwId interface{}
}

// A collection of values returned by getStaticRoute.
type GetStaticRouteResult struct {
	AwsGwId interface{}
	AzureGwId interface{}
	Description interface{}
	Destination interface{}
	GcpGwId interface{}
	InterdcGwId interface{}
	InternetGwId interface{}
	Name interface{}
	Nexthop interface{}
	Region interface{}
	ServiceType interface{}
	StaticRouteId interface{}
	TenantId interface{}
	VpnGwId interface{}
	// id is the provider-assigned unique ID for this managed resource.
	Id interface{}
}
