// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package network

import (
	"github.com/pkg/errors"
	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

type PublicIP struct {
	s *pulumi.ResourceState
}

// NewPublicIP registers a new resource with the given unique name, arguments, and options.
func NewPublicIP(ctx *pulumi.Context,
	name string, args *PublicIPArgs, opts ...pulumi.ResourceOpt) (*PublicIP, error) {
	if args == nil || args.InternetGwId == nil {
		return nil, errors.New("missing required argument 'InternetGwId'")
	}
	if args == nil || args.SubmaskLength == nil {
		return nil, errors.New("missing required argument 'SubmaskLength'")
	}
	inputs := make(map[string]interface{})
	if args == nil {
		inputs["description"] = nil
		inputs["internetGwId"] = nil
		inputs["name"] = nil
		inputs["region"] = nil
		inputs["submaskLength"] = nil
		inputs["tenantId"] = nil
	} else {
		inputs["description"] = args.Description
		inputs["internetGwId"] = args.InternetGwId
		inputs["name"] = args.Name
		inputs["region"] = args.Region
		inputs["submaskLength"] = args.SubmaskLength
		inputs["tenantId"] = args.TenantId
	}
	inputs["cidr"] = nil
	s, err := ctx.RegisterResource("ecl:network/publicIP:PublicIP", name, true, inputs, opts...)
	if err != nil {
		return nil, err
	}
	return &PublicIP{s: s}, nil
}

// GetPublicIP gets an existing PublicIP resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetPublicIP(ctx *pulumi.Context,
	name string, id pulumi.ID, state *PublicIPState, opts ...pulumi.ResourceOpt) (*PublicIP, error) {
	inputs := make(map[string]interface{})
	if state != nil {
		inputs["cidr"] = state.Cidr
		inputs["description"] = state.Description
		inputs["internetGwId"] = state.InternetGwId
		inputs["name"] = state.Name
		inputs["region"] = state.Region
		inputs["submaskLength"] = state.SubmaskLength
		inputs["tenantId"] = state.TenantId
	}
	s, err := ctx.ReadResource("ecl:network/publicIP:PublicIP", name, id, inputs, opts...)
	if err != nil {
		return nil, err
	}
	return &PublicIP{s: s}, nil
}

// URN is this resource's unique name assigned by Pulumi.
func (r *PublicIP) URN() *pulumi.URNOutput {
	return r.s.URN()
}

// ID is this resource's unique identifier assigned by its provider.
func (r *PublicIP) ID() *pulumi.IDOutput {
	return r.s.ID()
}

func (r *PublicIP) Cidr() *pulumi.StringOutput {
	return (*pulumi.StringOutput)(r.s.State["cidr"])
}

func (r *PublicIP) Description() *pulumi.StringOutput {
	return (*pulumi.StringOutput)(r.s.State["description"])
}

func (r *PublicIP) InternetGwId() *pulumi.StringOutput {
	return (*pulumi.StringOutput)(r.s.State["internetGwId"])
}

func (r *PublicIP) Name() *pulumi.StringOutput {
	return (*pulumi.StringOutput)(r.s.State["name"])
}

func (r *PublicIP) Region() *pulumi.StringOutput {
	return (*pulumi.StringOutput)(r.s.State["region"])
}

func (r *PublicIP) SubmaskLength() *pulumi.IntOutput {
	return (*pulumi.IntOutput)(r.s.State["submaskLength"])
}

func (r *PublicIP) TenantId() *pulumi.StringOutput {
	return (*pulumi.StringOutput)(r.s.State["tenantId"])
}

// Input properties used for looking up and filtering PublicIP resources.
type PublicIPState struct {
	Cidr interface{}
	Description interface{}
	InternetGwId interface{}
	Name interface{}
	Region interface{}
	SubmaskLength interface{}
	TenantId interface{}
}

// The set of arguments for constructing a PublicIP resource.
type PublicIPArgs struct {
	Description interface{}
	InternetGwId interface{}
	Name interface{}
	Region interface{}
	SubmaskLength interface{}
	TenantId interface{}
}
