// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package network

import (
	"github.com/pkg/errors"
	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

// Manages a V2 static route resource within Enterprise Cloud.
// > **Notice** We only support Static Route with service_type "internet" for now.
type StaticRoute struct {
	s *pulumi.ResourceState
}

// NewStaticRoute registers a new resource with the given unique name, arguments, and options.
func NewStaticRoute(ctx *pulumi.Context,
	name string, args *StaticRouteArgs, opts ...pulumi.ResourceOpt) (*StaticRoute, error) {
	if args == nil || args.Destination == nil {
		return nil, errors.New("missing required argument 'Destination'")
	}
	if args == nil || args.Nexthop == nil {
		return nil, errors.New("missing required argument 'Nexthop'")
	}
	if args == nil || args.ServiceType == nil {
		return nil, errors.New("missing required argument 'ServiceType'")
	}
	inputs := make(map[string]interface{})
	if args == nil {
		inputs["awsGwId"] = nil
		inputs["azureGwId"] = nil
		inputs["description"] = nil
		inputs["destination"] = nil
		inputs["gcpGwId"] = nil
		inputs["interdcGwId"] = nil
		inputs["internetGwId"] = nil
		inputs["name"] = nil
		inputs["nexthop"] = nil
		inputs["region"] = nil
		inputs["serviceType"] = nil
		inputs["tenantId"] = nil
		inputs["vpnGwId"] = nil
	} else {
		inputs["awsGwId"] = args.AwsGwId
		inputs["azureGwId"] = args.AzureGwId
		inputs["description"] = args.Description
		inputs["destination"] = args.Destination
		inputs["gcpGwId"] = args.GcpGwId
		inputs["interdcGwId"] = args.InterdcGwId
		inputs["internetGwId"] = args.InternetGwId
		inputs["name"] = args.Name
		inputs["nexthop"] = args.Nexthop
		inputs["region"] = args.Region
		inputs["serviceType"] = args.ServiceType
		inputs["tenantId"] = args.TenantId
		inputs["vpnGwId"] = args.VpnGwId
	}
	s, err := ctx.RegisterResource("ecl:network/staticRoute:StaticRoute", name, true, inputs, opts...)
	if err != nil {
		return nil, err
	}
	return &StaticRoute{s: s}, nil
}

// GetStaticRoute gets an existing StaticRoute resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetStaticRoute(ctx *pulumi.Context,
	name string, id pulumi.ID, state *StaticRouteState, opts ...pulumi.ResourceOpt) (*StaticRoute, error) {
	inputs := make(map[string]interface{})
	if state != nil {
		inputs["awsGwId"] = state.AwsGwId
		inputs["azureGwId"] = state.AzureGwId
		inputs["description"] = state.Description
		inputs["destination"] = state.Destination
		inputs["gcpGwId"] = state.GcpGwId
		inputs["interdcGwId"] = state.InterdcGwId
		inputs["internetGwId"] = state.InternetGwId
		inputs["name"] = state.Name
		inputs["nexthop"] = state.Nexthop
		inputs["region"] = state.Region
		inputs["serviceType"] = state.ServiceType
		inputs["tenantId"] = state.TenantId
		inputs["vpnGwId"] = state.VpnGwId
	}
	s, err := ctx.ReadResource("ecl:network/staticRoute:StaticRoute", name, id, inputs, opts...)
	if err != nil {
		return nil, err
	}
	return &StaticRoute{s: s}, nil
}

// URN is this resource's unique name assigned by Pulumi.
func (r *StaticRoute) URN() *pulumi.URNOutput {
	return r.s.URN()
}

// ID is this resource's unique identifier assigned by its provider.
func (r *StaticRoute) ID() *pulumi.IDOutput {
	return r.s.ID()
}

// AWS Gateway on which this static route will be set. Conflicts with "azure_gw_id", "gcp_gw_id", "interdc_gw_id", "internet_gw_id" and "vpn_gw_id".
func (r *StaticRoute) AwsGwId() *pulumi.StringOutput {
	return (*pulumi.StringOutput)(r.s.State["awsGwId"])
}

// Azure Gateway on which this static route will be set. Conflicts with "aws_gw_id", "gcp_gw_id", "interdc_gw_id", "internet_gw_id" and "vpn_gw_id".
func (r *StaticRoute) AzureGwId() *pulumi.StringOutput {
	return (*pulumi.StringOutput)(r.s.State["azureGwId"])
}

// Description of the Static Route resource.
func (r *StaticRoute) Description() *pulumi.StringOutput {
	return (*pulumi.StringOutput)(r.s.State["description"])
}

// CIDR this static route points to.
func (r *StaticRoute) Destination() *pulumi.StringOutput {
	return (*pulumi.StringOutput)(r.s.State["destination"])
}

// GCP Gateway on which this static route will be set. Conflicts with "aws_gw_id", "azure_gw_id", "interdc_gw_id", "internet_gw_id" and "vpn_gw_id".
func (r *StaticRoute) GcpGwId() *pulumi.StringOutput {
	return (*pulumi.StringOutput)(r.s.State["gcpGwId"])
}

// Inter DC Gateway on which this static route will be set. Conflicts with "aws_gw_id", "azure_gw_id", "gcp_gw_id", "internet_gw_id" and "vpn_gw_id".
func (r *StaticRoute) InterdcGwId() *pulumi.StringOutput {
	return (*pulumi.StringOutput)(r.s.State["interdcGwId"])
}

// Internet Gateway on which this static route will be set. Conflicts with "aws_gw_id", "azure_gw_id", "gcp_gw_id", "interdc_gw_id" and "vpn_gw_id".
func (r *StaticRoute) InternetGwId() *pulumi.StringOutput {
	return (*pulumi.StringOutput)(r.s.State["internetGwId"])
}

// Name of the Static Route resource.
func (r *StaticRoute) Name() *pulumi.StringOutput {
	return (*pulumi.StringOutput)(r.s.State["name"])
}

// Next Hop address for specified CIDR.
func (r *StaticRoute) Nexthop() *pulumi.StringOutput {
	return (*pulumi.StringOutput)(r.s.State["nexthop"])
}

// The region in which to obtain the V2 Network client.
// Public ips are associated with accounts, but a Network client is needed to
// create one. If omitted, the `region` argument of the provider is used.
// Changing this creates a new public ip.
func (r *StaticRoute) Region() *pulumi.StringOutput {
	return (*pulumi.StringOutput)(r.s.State["region"])
}

// Service type for this route. Must be one of "aws", "azure", "gcp", "interdc", "internet" and "vpn".
func (r *StaticRoute) ServiceType() *pulumi.StringOutput {
	return (*pulumi.StringOutput)(r.s.State["serviceType"])
}

// Tenant ID of the owner (UUID).
func (r *StaticRoute) TenantId() *pulumi.StringOutput {
	return (*pulumi.StringOutput)(r.s.State["tenantId"])
}

// VPN Gateway on which this static route will be set. Conflicts with "aws_gw_id", "azure_gw_id", "gcp_gw_id", "interdc_gw_id" and "internet_gw_id".
func (r *StaticRoute) VpnGwId() *pulumi.StringOutput {
	return (*pulumi.StringOutput)(r.s.State["vpnGwId"])
}

// Input properties used for looking up and filtering StaticRoute resources.
type StaticRouteState struct {
	// AWS Gateway on which this static route will be set. Conflicts with "azure_gw_id", "gcp_gw_id", "interdc_gw_id", "internet_gw_id" and "vpn_gw_id".
	AwsGwId interface{}
	// Azure Gateway on which this static route will be set. Conflicts with "aws_gw_id", "gcp_gw_id", "interdc_gw_id", "internet_gw_id" and "vpn_gw_id".
	AzureGwId interface{}
	// Description of the Static Route resource.
	Description interface{}
	// CIDR this static route points to.
	Destination interface{}
	// GCP Gateway on which this static route will be set. Conflicts with "aws_gw_id", "azure_gw_id", "interdc_gw_id", "internet_gw_id" and "vpn_gw_id".
	GcpGwId interface{}
	// Inter DC Gateway on which this static route will be set. Conflicts with "aws_gw_id", "azure_gw_id", "gcp_gw_id", "internet_gw_id" and "vpn_gw_id".
	InterdcGwId interface{}
	// Internet Gateway on which this static route will be set. Conflicts with "aws_gw_id", "azure_gw_id", "gcp_gw_id", "interdc_gw_id" and "vpn_gw_id".
	InternetGwId interface{}
	// Name of the Static Route resource.
	Name interface{}
	// Next Hop address for specified CIDR.
	Nexthop interface{}
	// The region in which to obtain the V2 Network client.
	// Public ips are associated with accounts, but a Network client is needed to
	// create one. If omitted, the `region` argument of the provider is used.
	// Changing this creates a new public ip.
	Region interface{}
	// Service type for this route. Must be one of "aws", "azure", "gcp", "interdc", "internet" and "vpn".
	ServiceType interface{}
	// Tenant ID of the owner (UUID).
	TenantId interface{}
	// VPN Gateway on which this static route will be set. Conflicts with "aws_gw_id", "azure_gw_id", "gcp_gw_id", "interdc_gw_id" and "internet_gw_id".
	VpnGwId interface{}
}

// The set of arguments for constructing a StaticRoute resource.
type StaticRouteArgs struct {
	// AWS Gateway on which this static route will be set. Conflicts with "azure_gw_id", "gcp_gw_id", "interdc_gw_id", "internet_gw_id" and "vpn_gw_id".
	AwsGwId interface{}
	// Azure Gateway on which this static route will be set. Conflicts with "aws_gw_id", "gcp_gw_id", "interdc_gw_id", "internet_gw_id" and "vpn_gw_id".
	AzureGwId interface{}
	// Description of the Static Route resource.
	Description interface{}
	// CIDR this static route points to.
	Destination interface{}
	// GCP Gateway on which this static route will be set. Conflicts with "aws_gw_id", "azure_gw_id", "interdc_gw_id", "internet_gw_id" and "vpn_gw_id".
	GcpGwId interface{}
	// Inter DC Gateway on which this static route will be set. Conflicts with "aws_gw_id", "azure_gw_id", "gcp_gw_id", "internet_gw_id" and "vpn_gw_id".
	InterdcGwId interface{}
	// Internet Gateway on which this static route will be set. Conflicts with "aws_gw_id", "azure_gw_id", "gcp_gw_id", "interdc_gw_id" and "vpn_gw_id".
	InternetGwId interface{}
	// Name of the Static Route resource.
	Name interface{}
	// Next Hop address for specified CIDR.
	Nexthop interface{}
	// The region in which to obtain the V2 Network client.
	// Public ips are associated with accounts, but a Network client is needed to
	// create one. If omitted, the `region` argument of the provider is used.
	// Changing this creates a new public ip.
	Region interface{}
	// Service type for this route. Must be one of "aws", "azure", "gcp", "interdc", "internet" and "vpn".
	ServiceType interface{}
	// Tenant ID of the owner (UUID).
	TenantId interface{}
	// VPN Gateway on which this static route will be set. Conflicts with "aws_gw_id", "azure_gw_id", "gcp_gw_id", "interdc_gw_id" and "internet_gw_id".
	VpnGwId interface{}
}
