# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import json
import warnings
import pulumi
import pulumi.runtime
from .. import utilities, tables

class Zone(pulumi.CustomResource):
    description: pulumi.Output[str]
    """
    Description for this zone.
    """
    email: pulumi.Output[str]
    """
    E-mail for the zone.
    Used in SOA records for the zone.
    This parameter is not currently supported.
    Even if you set this parameter, it will be ignored.
    """
    masters: pulumi.Output[list]
    """
    For secondary zones. 
    The servers to slave from to get DNS information.
    """
    name: pulumi.Output[str]
    """
    DNS Name for the zone.
    """
    ttl: pulumi.Output[float]
    """
    TTL (Time to Live) for the zone.
    This parameter is not currently supported.
    Even if you set this parameter, it will be ignored.
    """
    type: pulumi.Output[str]
    """
    Type of zone.
    PRIMARY is controlled by ECL2.0 DNS,
    SECONDARY zones are slaved from another DNS Server.
    Defaults to PRIMARY.
    This parameter is not currently supported.
    Even if you set this parameter, it will be ignored.
    """
    def __init__(__self__, resource_name, opts=None, description=None, email=None, masters=None, name=None, ttl=None, type=None, __name__=None, __opts__=None):
        """
        Manages a V2 zone resource of Enterprise Cloud.
        
        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[str] description: Description for this zone.
        :param pulumi.Input[str] email: E-mail for the zone.
               Used in SOA records for the zone.
               This parameter is not currently supported.
               Even if you set this parameter, it will be ignored.
        :param pulumi.Input[list] masters: For secondary zones. 
               The servers to slave from to get DNS information.
        :param pulumi.Input[str] name: DNS Name for the zone.
        :param pulumi.Input[float] ttl: TTL (Time to Live) for the zone.
               This parameter is not currently supported.
               Even if you set this parameter, it will be ignored.
        :param pulumi.Input[str] type: Type of zone.
               PRIMARY is controlled by ECL2.0 DNS,
               SECONDARY zones are slaved from another DNS Server.
               Defaults to PRIMARY.
               This parameter is not currently supported.
               Even if you set this parameter, it will be ignored.
        """
        if __name__ is not None:
            warnings.warn("explicit use of __name__ is deprecated", DeprecationWarning)
            resource_name = __name__
        if __opts__ is not None:
            warnings.warn("explicit use of __opts__ is deprecated, use 'opts' instead", DeprecationWarning)
            opts = __opts__
        if not resource_name:
            raise TypeError('Missing resource name argument (for URN creation)')
        if not isinstance(resource_name, str):
            raise TypeError('Expected resource name to be a string')
        if opts and not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')

        __props__ = dict()

        __props__['description'] = description

        __props__['email'] = email

        __props__['masters'] = masters

        __props__['name'] = name

        __props__['ttl'] = ttl

        __props__['type'] = type

        super(Zone, __self__).__init__(
            'ecl:dns/zone:Zone',
            resource_name,
            __props__,
            opts)


    def translate_output_property(self, prop):
        return tables._CAMEL_TO_SNAKE_CASE_TABLE.get(prop) or prop

    def translate_input_property(self, prop):
        return tables._SNAKE_TO_CAMEL_CASE_TABLE.get(prop) or prop

