# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import pulumi
import pulumi.runtime
from .. import utilities

class GetCommonFunctionGatwayResult(object):
    """
    A collection of values returned by getCommonFunctionGatway.
    """
    def __init__(__self__, common_function_pool_id=None, description=None, name=None, network_id=None, subnet_id=None, tenant_id=None, id=None):
        if common_function_pool_id and not isinstance(common_function_pool_id, basestring):
            raise TypeError('Expected argument common_function_pool_id to be a basestring')
        __self__.common_function_pool_id = common_function_pool_id
        if description and not isinstance(description, basestring):
            raise TypeError('Expected argument description to be a basestring')
        __self__.description = description
        if name and not isinstance(name, basestring):
            raise TypeError('Expected argument name to be a basestring')
        __self__.name = name
        if network_id and not isinstance(network_id, basestring):
            raise TypeError('Expected argument network_id to be a basestring')
        __self__.network_id = network_id
        if subnet_id and not isinstance(subnet_id, basestring):
            raise TypeError('Expected argument subnet_id to be a basestring')
        __self__.subnet_id = subnet_id
        if tenant_id and not isinstance(tenant_id, basestring):
            raise TypeError('Expected argument tenant_id to be a basestring')
        __self__.tenant_id = tenant_id
        if id and not isinstance(id, basestring):
            raise TypeError('Expected argument id to be a basestring')
        __self__.id = id
        """
        id is the provider-assigned unique ID for this managed resource.
        """

def get_common_function_gatway(common_function_pool_id=None, description=None, name=None, network_id=None, subnet_id=None, tenant_id=None):
    __args__ = dict()

    __args__['commonFunctionPoolId'] = common_function_pool_id
    __args__['description'] = description
    __args__['name'] = name
    __args__['networkId'] = network_id
    __args__['subnetId'] = subnet_id
    __args__['tenantId'] = tenant_id
    __ret__ = pulumi.runtime.invoke('ecl:network/getCommonFunctionGatway:getCommonFunctionGatway', __args__)

    return GetCommonFunctionGatwayResult(
        common_function_pool_id=__ret__.get('commonFunctionPoolId'),
        description=__ret__.get('description'),
        name=__ret__.get('name'),
        network_id=__ret__.get('networkId'),
        subnet_id=__ret__.get('subnetId'),
        tenant_id=__ret__.get('tenantId'),
        id=__ret__.get('id'))
