# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import json
import warnings
import pulumi
import pulumi.runtime
from .. import utilities, tables

class Network(pulumi.CustomResource):
    admin_state_up: pulumi.Output[str]
    description: pulumi.Output[str]
    name: pulumi.Output[str]
    plane: pulumi.Output[str]
    status: pulumi.Output[str]
    subnets: pulumi.Output[list]
    tags: pulumi.Output[dict]
    tenant_id: pulumi.Output[str]
    def __init__(__self__, resource_name, opts=None, admin_state_up=None, description=None, name=None, plane=None, status=None, subnets=None, tags=None, tenant_id=None, __name__=None, __opts__=None):
        """
        Create a Network resource with the given unique name, props, and options.
        
        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[str] admin_state_up
        :param pulumi.Input[str] description
        :param pulumi.Input[str] name
        :param pulumi.Input[str] plane
        :param pulumi.Input[str] status
        :param pulumi.Input[list] subnets
        :param pulumi.Input[dict] tags
        :param pulumi.Input[str] tenant_id
        """
        if __name__ is not None:
            warnings.warn("explicit use of __name__ is deprecated", DeprecationWarning)
            resource_name = __name__
        if __opts__ is not None:
            warnings.warn("explicit use of __opts__ is deprecated, use 'opts' instead", DeprecationWarning)
            opts = __opts__
        if not resource_name:
            raise TypeError('Missing resource name argument (for URN creation)')
        if not isinstance(resource_name, str):
            raise TypeError('Expected resource name to be a string')
        if opts and not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')

        __props__ = dict()

        __props__['admin_state_up'] = admin_state_up

        __props__['description'] = description

        __props__['name'] = name

        __props__['plane'] = plane

        __props__['status'] = status

        __props__['subnets'] = subnets

        __props__['tags'] = tags

        __props__['tenant_id'] = tenant_id

        super(Network, __self__).__init__(
            'ecl:network/network:Network',
            resource_name,
            __props__,
            opts)


    def translate_output_property(self, prop):
        return tables._CAMEL_TO_SNAKE_CASE_TABLE.get(prop) or prop

    def translate_input_property(self, prop):
        return tables._SNAKE_TO_CAMEL_CASE_TABLE.get(prop) or prop

