# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import pulumi
import pulumi.runtime
from .. import utilities

class PublicIP(pulumi.CustomResource):
    def __init__(__self__, __name__, __opts__=None, description=None, internet_gw_id=None, name=None, region=None, submask_length=None, tenant_id=None):
        """Create a PublicIP resource with the given unique name, props, and options."""
        if not __name__:
            raise TypeError('Missing resource name argument (for URN creation)')
        if not isinstance(__name__, basestring):
            raise TypeError('Expected resource name to be a string')
        if __opts__ and not isinstance(__opts__, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')

        __props__ = dict()

        if description and not isinstance(description, basestring):
            raise TypeError('Expected property description to be a basestring')
        __self__.description = description
        __props__['description'] = description

        if not internet_gw_id:
            raise TypeError('Missing required property internet_gw_id')
        elif not isinstance(internet_gw_id, basestring):
            raise TypeError('Expected property internet_gw_id to be a basestring')
        __self__.internet_gw_id = internet_gw_id
        __props__['internetGwId'] = internet_gw_id

        if name and not isinstance(name, basestring):
            raise TypeError('Expected property name to be a basestring')
        __self__.name = name
        __props__['name'] = name

        if region and not isinstance(region, basestring):
            raise TypeError('Expected property region to be a basestring')
        __self__.region = region
        __props__['region'] = region

        if not submask_length:
            raise TypeError('Missing required property submask_length')
        elif not isinstance(submask_length, int):
            raise TypeError('Expected property submask_length to be a int')
        __self__.submask_length = submask_length
        __props__['submaskLength'] = submask_length

        if tenant_id and not isinstance(tenant_id, basestring):
            raise TypeError('Expected property tenant_id to be a basestring')
        __self__.tenant_id = tenant_id
        __props__['tenantId'] = tenant_id

        __self__.cidr = pulumi.runtime.UNKNOWN

        super(PublicIP, __self__).__init__(
            'ecl:network/publicIP:PublicIP',
            __name__,
            __props__,
            __opts__)

    def set_outputs(self, outs):
        if 'cidr' in outs:
            self.cidr = outs['cidr']
        if 'description' in outs:
            self.description = outs['description']
        if 'internetGwId' in outs:
            self.internet_gw_id = outs['internetGwId']
        if 'name' in outs:
            self.name = outs['name']
        if 'region' in outs:
            self.region = outs['region']
        if 'submaskLength' in outs:
            self.submask_length = outs['submaskLength']
        if 'tenantId' in outs:
            self.tenant_id = outs['tenantId']
