# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import pulumi
import pulumi.runtime
from .. import utilities

class StaticRoute(pulumi.CustomResource):
    def __init__(__self__, __name__, __opts__=None, aws_gw_id=None, azure_gw_id=None, description=None, destination=None, gcp_gw_id=None, interdc_gw_id=None, internet_gw_id=None, name=None, nexthop=None, region=None, service_type=None, tenant_id=None, vpn_gw_id=None):
        """Create a StaticRoute resource with the given unique name, props, and options."""
        if not __name__:
            raise TypeError('Missing resource name argument (for URN creation)')
        if not isinstance(__name__, basestring):
            raise TypeError('Expected resource name to be a string')
        if __opts__ and not isinstance(__opts__, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')

        __props__ = dict()

        if aws_gw_id and not isinstance(aws_gw_id, basestring):
            raise TypeError('Expected property aws_gw_id to be a basestring')
        __self__.aws_gw_id = aws_gw_id
        __props__['awsGwId'] = aws_gw_id

        if azure_gw_id and not isinstance(azure_gw_id, basestring):
            raise TypeError('Expected property azure_gw_id to be a basestring')
        __self__.azure_gw_id = azure_gw_id
        __props__['azureGwId'] = azure_gw_id

        if description and not isinstance(description, basestring):
            raise TypeError('Expected property description to be a basestring')
        __self__.description = description
        __props__['description'] = description

        if not destination:
            raise TypeError('Missing required property destination')
        elif not isinstance(destination, basestring):
            raise TypeError('Expected property destination to be a basestring')
        __self__.destination = destination
        __props__['destination'] = destination

        if gcp_gw_id and not isinstance(gcp_gw_id, basestring):
            raise TypeError('Expected property gcp_gw_id to be a basestring')
        __self__.gcp_gw_id = gcp_gw_id
        __props__['gcpGwId'] = gcp_gw_id

        if interdc_gw_id and not isinstance(interdc_gw_id, basestring):
            raise TypeError('Expected property interdc_gw_id to be a basestring')
        __self__.interdc_gw_id = interdc_gw_id
        __props__['interdcGwId'] = interdc_gw_id

        if internet_gw_id and not isinstance(internet_gw_id, basestring):
            raise TypeError('Expected property internet_gw_id to be a basestring')
        __self__.internet_gw_id = internet_gw_id
        __props__['internetGwId'] = internet_gw_id

        if name and not isinstance(name, basestring):
            raise TypeError('Expected property name to be a basestring')
        __self__.name = name
        __props__['name'] = name

        if not nexthop:
            raise TypeError('Missing required property nexthop')
        elif not isinstance(nexthop, basestring):
            raise TypeError('Expected property nexthop to be a basestring')
        __self__.nexthop = nexthop
        __props__['nexthop'] = nexthop

        if region and not isinstance(region, basestring):
            raise TypeError('Expected property region to be a basestring')
        __self__.region = region
        __props__['region'] = region

        if not service_type:
            raise TypeError('Missing required property service_type')
        elif not isinstance(service_type, basestring):
            raise TypeError('Expected property service_type to be a basestring')
        __self__.service_type = service_type
        __props__['serviceType'] = service_type

        if tenant_id and not isinstance(tenant_id, basestring):
            raise TypeError('Expected property tenant_id to be a basestring')
        __self__.tenant_id = tenant_id
        __props__['tenantId'] = tenant_id

        if vpn_gw_id and not isinstance(vpn_gw_id, basestring):
            raise TypeError('Expected property vpn_gw_id to be a basestring')
        __self__.vpn_gw_id = vpn_gw_id
        __props__['vpnGwId'] = vpn_gw_id

        super(StaticRoute, __self__).__init__(
            'ecl:network/staticRoute:StaticRoute',
            __name__,
            __props__,
            __opts__)

    def set_outputs(self, outs):
        if 'awsGwId' in outs:
            self.aws_gw_id = outs['awsGwId']
        if 'azureGwId' in outs:
            self.azure_gw_id = outs['azureGwId']
        if 'description' in outs:
            self.description = outs['description']
        if 'destination' in outs:
            self.destination = outs['destination']
        if 'gcpGwId' in outs:
            self.gcp_gw_id = outs['gcpGwId']
        if 'interdcGwId' in outs:
            self.interdc_gw_id = outs['interdcGwId']
        if 'internetGwId' in outs:
            self.internet_gw_id = outs['internetGwId']
        if 'name' in outs:
            self.name = outs['name']
        if 'nexthop' in outs:
            self.nexthop = outs['nexthop']
        if 'region' in outs:
            self.region = outs['region']
        if 'serviceType' in outs:
            self.service_type = outs['serviceType']
        if 'tenantId' in outs:
            self.tenant_id = outs['tenantId']
        if 'vpnGwId' in outs:
            self.vpn_gw_id = outs['vpnGwId']
