# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import pulumi
import pulumi.runtime
from .. import utilities

class GetVirtualStorageResult(object):
    """
    A collection of values returned by getVirtualStorage.
    """
    def __init__(__self__, id=None):
        if id and not isinstance(id, basestring):
            raise TypeError('Expected argument id to be a basestring')
        __self__.id = id
        """
        id is the provider-assigned unique ID for this managed resource.
        """

def get_virtual_storage(description=None, host_routes=None, ip_addr_pool=None, name=None, network_id=None, subnet_id=None, virtual_storage_id=None, volume_type_id=None):
    __args__ = dict()

    __args__['description'] = description
    __args__['hostRoutes'] = host_routes
    __args__['ipAddrPool'] = ip_addr_pool
    __args__['name'] = name
    __args__['networkId'] = network_id
    __args__['subnetId'] = subnet_id
    __args__['virtualStorageId'] = virtual_storage_id
    __args__['volumeTypeId'] = volume_type_id
    __ret__ = pulumi.runtime.invoke('ecl:storage/getVirtualStorage:getVirtualStorage', __args__)

    return GetVirtualStorageResult(
        id=__ret__.get('id'))
