# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import pulumi
import pulumi.runtime
from .. import utilities

class GetVolumeResult(object):
    """
    A collection of values returned by getVolume.
    """
    def __init__(__self__, availability_zone=None, id=None):
        if availability_zone and not isinstance(availability_zone, basestring):
            raise TypeError('Expected argument availability_zone to be a basestring')
        __self__.availability_zone = availability_zone
        if id and not isinstance(id, basestring):
            raise TypeError('Expected argument id to be a basestring')
        __self__.id = id
        """
        id is the provider-assigned unique ID for this managed resource.
        """

def get_volume(availability_zone=None, description=None, initiator_iqns=None, iops_per_gb=None, name=None, size=None, throughput=None, virtual_storage_id=None, volume_id=None):
    __args__ = dict()

    __args__['availabilityZone'] = availability_zone
    __args__['description'] = description
    __args__['initiatorIqns'] = initiator_iqns
    __args__['iopsPerGb'] = iops_per_gb
    __args__['name'] = name
    __args__['size'] = size
    __args__['throughput'] = throughput
    __args__['virtualStorageId'] = virtual_storage_id
    __args__['volumeId'] = volume_id
    __ret__ = pulumi.runtime.invoke('ecl:storage/getVolume:getVolume', __args__)

    return GetVolumeResult(
        availability_zone=__ret__.get('availabilityZone'),
        id=__ret__.get('id'))
