// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

export function getInternetGateway(args?: GetInternetGatewayArgs, opts?: pulumi.InvokeOptions): Promise<GetInternetGatewayResult> {
    args = args || {};
    return pulumi.runtime.invoke("ecl:network/getInternetGateway:getInternetGateway", {
        "description": args.description,
        "internetGatewayId": args.internetGatewayId,
        "internetServiceId": args.internetServiceId,
        "name": args.name,
        "qosOptionId": args.qosOptionId,
        "region": args.region,
        "status": args.status,
        "tenantId": args.tenantId,
    }, opts);
}

/**
 * A collection of arguments for invoking getInternetGateway.
 */
export interface GetInternetGatewayArgs {
    readonly description?: string;
    readonly internetGatewayId?: string;
    readonly internetServiceId?: string;
    readonly name?: string;
    readonly qosOptionId?: string;
    readonly region?: string;
    readonly status?: string;
    readonly tenantId?: string;
}

/**
 * A collection of values returned by getInternetGateway.
 */
export interface GetInternetGatewayResult {
    readonly description: string;
    readonly internetGatewayId: string;
    readonly internetServiceId: string;
    readonly name: string;
    readonly qosOptionId: string;
    readonly region: string;
    readonly status: string;
    readonly tenantId: string;
    /**
     * id is the provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
}
