// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

export function getPublicIP(args?: GetPublicIPArgs, opts?: pulumi.InvokeOptions): Promise<GetPublicIPResult> {
    args = args || {};
    return pulumi.runtime.invoke("ecl:network/getPublicIP:getPublicIP", {
        "cidr": args.cidr,
        "description": args.description,
        "internetGwId": args.internetGwId,
        "name": args.name,
        "publicIpId": args.publicIpId,
        "region": args.region,
        "status": args.status,
        "submaskLength": args.submaskLength,
        "tenantId": args.tenantId,
    }, opts);
}

/**
 * A collection of arguments for invoking getPublicIP.
 */
export interface GetPublicIPArgs {
    readonly cidr?: string;
    readonly description?: string;
    readonly internetGwId?: string;
    readonly name?: string;
    readonly publicIpId?: string;
    readonly region?: string;
    readonly status?: string;
    readonly submaskLength?: number;
    readonly tenantId?: string;
}

/**
 * A collection of values returned by getPublicIP.
 */
export interface GetPublicIPResult {
    readonly cidr: string;
    readonly description: string;
    readonly internetGwId: string;
    readonly name: string;
    readonly publicIpId: string;
    readonly region: string;
    readonly status: string;
    readonly submaskLength: number;
    readonly tenantId: string;
    /**
     * id is the provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
}
