// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

// Export members:
export * from "./provider";

// Export sub-modules:
import * as compute from "./compute/index";
import * as config from "./config/index";
import * as dns from "./dns/index";
import * as imagestorages from "./imagestorages/index";
import * as network from "./network/index";
import * as sss from "./sss/index";
import * as storage from "./storage/index";
export {compute, config, dns, imagestorages, network, sss, storage};
